package com.huoli.openapi.vo.data;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable{
    /**
     * 
     */
    private static final long serialVersionUID = -5174378689613008037L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    private String token;
    private Long loginUid;
    private Long lastOperateTime;
    
    public String getToken() {
		return token;
	}

	public Long getLoginUid() {
		return loginUid;
	}

	public Long getLastOperateTime() {
		return lastOperateTime;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public void setLoginUid(Long loginUid) {
		this.loginUid = loginUid;
	}

	public void setLastOperateTime(Long lastOperateTime) {
		this.lastOperateTime = lastOperateTime;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.reg_time
     *
     * @mbggenerated
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.platform
     *
     * @mbggenerated
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.imei
     *
     * @mbggenerated
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.imsi
     *
     * @mbggenerated
     */
    private String imsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ptype
     *
     * @mbggenerated
     */
    private String ptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ctype
     *
     * @mbggenerated
     */
    private String ctype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.uid
     *
     * @return the value of user_info.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.uid
     *
     * @param uid the value for user_info.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.reg_time
     *
     * @return the value of user_info.reg_time
     *
     * @mbggenerated
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.reg_time
     *
     * @param regTime the value for user_info.reg_time
     *
     * @mbggenerated
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.platform
     *
     * @return the value of user_info.platform
     *
     * @mbggenerated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.platform
     *
     * @param platform the value for user_info.platform
     *
     * @mbggenerated
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.source
     *
     * @return the value of user_info.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.source
     *
     * @param source the value for user_info.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.imei
     *
     * @return the value of user_info.imei
     *
     * @mbggenerated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.imei
     *
     * @param imei the value for user_info.imei
     *
     * @mbggenerated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.imsi
     *
     * @return the value of user_info.imsi
     *
     * @mbggenerated
     */
    public String getImsi() {
        return imsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.imsi
     *
     * @param imsi the value for user_info.imsi
     *
     * @mbggenerated
     */
    public void setImsi(String imsi) {
        this.imsi = imsi == null ? null : imsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ptype
     *
     * @return the value of user_info.ptype
     *
     * @mbggenerated
     */
    public String getPtype() {
        return ptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ptype
     *
     * @param ptype the value for user_info.ptype
     *
     * @mbggenerated
     */
    public void setPtype(String ptype) {
        this.ptype = ptype == null ? null : ptype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ctype
     *
     * @return the value of user_info.ctype
     *
     * @mbggenerated
     */
    public String getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ctype
     *
     * @param ctype the value for user_info.ctype
     *
     * @mbggenerated
     */
    public void setCtype(String ctype) {
        this.ctype = ctype == null ? null : ctype.trim();
    }
}